services:
  web:
    build:
      context: ./Django
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - ./Django/.env
    expose:
      - "8000"
    networks:
      - my_network
    # entrypoint: ["/app/entrypoint.sh"]

  nginx:
    image: nginx:latest
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my_network
    depends_on:
      - web

volumes:
  static_volume:

networks:
  my_network:

