# Generated by Django 5.0.7 on 2024-09-14 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('module', models.IntegerField(choices=[(1, 'Patient Care'), (2, 'Safety'), (3, 'Image Production'), (4, 'Procedures')])),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Multiple Choice Question'), (2, 'Multiple Select Question'), (3, 'True or False')], default=1)),
                ('option_a', models.CharField(max_length=128)),
                ('option_b', models.CharField(max_length=128)),
                ('option_c', models.CharField(blank=True, max_length=128, null=True)),
                ('option_d', models.CharField(blank=True, max_length=128, null=True)),
                ('answer_key', models.CharField(max_length=4)),
                ('obsolete_ind', models.BooleanField(default=False)),
                ('created_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='common.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_dt_tm', models.DateTimeField(null=True)),
                ('end_dt_tm', models.DateTimeField(null=True)),
                ('score', models.FloatField(null=True)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=None, null=True)),
                ('elapsed_time', models.DurationField(null=True)),
                ('question', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='common.question')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='common.test')),
            ],
        ),
    ]
